# Generated by Django 3.1.2 on 2020-11-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='foto',
            field=models.ImageField(default='', upload_to='libros'),
            preserve_default=False,
        ),
    ]
